annotations:
  group: fun.freechat
cert:
  manager:
    namespace: cert-manager
    version: v1.16.1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: freechat-llm-letsencrypt-http01
  className: nginx
  enabled: false
  hosts:
    - host: llm.freechat.fun
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - llm.freechat.fun
      secretName: freechat-llm-tls
podSecurityContext:
  fsGroup: 10000
replicaCount: 1
serviceAccount:
  create: true
  automount: false
ollama:
  gpu:
    enabled: true
    type: 'nvidia'
    number: 1
